<?php
/**
 * Template part for displaying the Booking section
 *
 * @package KM_Personal
 */

// Get ACF fields
$booking_heading = get_field('booking_heading');
$booking_subtitle = get_field('booking_subtitle');
$booking_type = get_field('booking_type'); // 'calendly' or 'custom'
$calendly_url = get_field('calendly_url');
$booking_description = get_field('booking_description');

// Set defaults
$booking_heading = $booking_heading ?: 'BRONEERI TASUTA KONSULTATSIOON';
$booking_subtitle = $booking_subtitle ?: 'Vali sobiv aeg ja broneeri 30-minutiline tasuta konsultatsioon. Räägime sinu ettevõtte vajadustest ja leiame parimad lahendused.';
$booking_type = $booking_type ?: 'calendly';
$calendly_url = $calendly_url ?: 'https://calendly.com/your-username';
?>

<section class="booking" id="broneerimine">
    <div class="container">

        <?php if ($booking_heading) : ?>
            <h2 class="section-title">
                <?php echo esc_html($booking_heading); ?>
            </h2>
        <?php endif; ?>

        <?php if ($booking_subtitle) : ?>
            <p class="section-subtitle">
                <?php echo esc_html($booking_subtitle); ?>
            </p>
        <?php endif; ?>

        <?php if ($booking_description) : ?>
            <div class="booking-description">
                <?php echo wp_kses_post($booking_description); ?>
            </div>
        <?php endif; ?>

        <div class="booking-container">

            <?php if ($booking_type === 'calendly' && $calendly_url) : ?>

                <!-- Calendly Inline Widget -->
                <div class="calendly-inline-widget"
                     data-url="<?php echo esc_url($calendly_url); ?>?hide_gdpr_banner=1&primary_color=214945"
                     style="min-width:320px;height:700px;">
                </div>

                <!-- Calendly Script -->
                <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>

            <?php elseif ($booking_type === 'custom') : ?>

                <!-- Custom Booking Calendar -->
                <div class="custom-booking">

                    <div class="booking-grid">

                        <!-- Calendar Side -->
                        <div class="calendar-side">
                            <div class="calendar-header">
                                <button class="calendar-nav prev" id="prevMonth">
                                    <i class="fas fa-chevron-left"></i>
                                </button>
                                <h3 class="calendar-month" id="currentMonth">Oktoober 2024</h3>
                                <button class="calendar-nav next" id="nextMonth">
                                    <i class="fas fa-chevron-right"></i>
                                </button>
                            </div>

                            <div class="calendar-weekdays">
                                <div class="weekday">E</div>
                                <div class="weekday">T</div>
                                <div class="weekday">K</div>
                                <div class="weekday">N</div>
                                <div class="weekday">R</div>
                                <div class="weekday">L</div>
                                <div class="weekday">P</div>
                            </div>

                            <div class="calendar-days" id="calendarDays">
                                <!-- Days will be generated by JavaScript -->
                            </div>
                        </div>

                        <!-- Time Slots Side -->
                        <div class="timeslots-side">
                            <h4 class="timeslots-title">Vali sobiv kellaaeg</h4>
                            <p class="selected-date" id="selectedDate">Vali esmalt kuupäev</p>

                            <div class="timeslots-container" id="timeslotsContainer">
                                <!-- Time slots will be generated by JavaScript -->
                            </div>

                            <div class="booking-form" id="bookingForm" style="display:none;">
                                <h4>Sinu andmed</h4>
                                <form id="appointmentForm">
                                    <input type="hidden" id="selectedDateTime" name="datetime">

                                    <div class="form-group">
                                        <label for="name">Nimi *</label>
                                        <input type="text" id="name" name="name" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="email">E-mail *</label>
                                        <input type="email" id="email" name="email" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="phone">Telefon *</label>
                                        <input type="tel" id="phone" name="phone" required>
                                    </div>

                                    <div class="form-group">
                                        <label for="message">Lühike kirjeldus (valikuline)</label>
                                        <textarea id="message" name="message" rows="3"></textarea>
                                    </div>

                                    <button type="submit" class="btn btn-primary btn-large">
                                        Kinnita broneering
                                    </button>
                                </form>
                            </div>
                        </div>

                    </div>

                </div>

            <?php else : ?>

                <!-- Fallback: Simple Contact Button -->
                <div class="booking-fallback">
                    <p>Broneerimiskalender tulekohta!</p>
                    <a href="#kontakt" class="btn btn-primary btn-large">Võta ühendust</a>
                </div>

            <?php endif; ?>

        </div>

    </div>
</section>
